scrape_configs:
  - job_name: 'account-service-application'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s # This can be adjusted based on our needs
    static_configs:
      - targets: ['host.docker.internal:8080']
  - job_name: 'notification-service-application'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s # This can be adjusted based on our needs
    static_configs:
      - targets: ['host.docker.internal:8083']